FROM ubuntu:24.04

# From .env
ARG USER
ARG CLI
ARG PSDK
ARG FLUTTER

# Install bash dependencies
RUN apt update
RUN apt install -y sudo adduser

# Add config sudoers for check Flutter
RUN printf '\n\
'${USER}' ALL=(ALL) NOPASSWD: /home/'${USER}'/AuroraPlatformSDK-'${PSDK}'/sdks/aurora_psdk/sdk-chroot\n\
Defaults!/home/'${USER}'/AuroraPlatformSDK-'${PSDK}'/sdks/aurora_psdk/sdk-chroot env_keep += "SSH_AGENT_PID SSH_AUTH_SOCK"\n\
' >> /etc/sudoers.d/sdk-chroot
RUN printf '\n\
'${USER}' ALL=(ALL) NOPASSWD: /home/'${USER}'/AuroraPlatformSDK-'${PSDK}'/sdks/aurora_psdk\n\
Defaults!/home/'${USER}'/AuroraPlatformSDK-'${PSDK}'/sdks/aurora_psdk env_keep += "SSH_AGENT_PID SSH_AUTH_SOCK"\n\
' >> /etc/sudoers.d/mer-sdk-chroot

# Add user
RUN adduser --disabled-password --gecos '' ${USER}
RUN echo "${USER} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${USER}

# Set user
USER ${USER}
ENV USER=${USER}
WORKDIR /home/${USER}

# Install dependencies
RUN sudo apt install -y \
    git \
    git-lfs \
    ssh \
    curl \
    tar \
    unzip \
    bzip2 \
    clang-format

# Install Aurora CLI
ENV LANG="en_US"
RUN sudo apt install python3-pip -y
RUN python3 -m pip install --upgrade setuptools --break-system-packages
RUN python3 -m pip install aurora-cli==${CLI} --break-system-packages
ENV PATH="/home/${USER}/.local/bin:$PATH"

# Download PSDK, preparing for installation
RUN test $(aurora-cli api --route="/psdk/download?version=${PSDK}" | grep "code" | tail -n 1 | xargs | sed 's/,//g' | sed 's/code: //g') -eq 200 || exit 1
ENV PSDK_DIR="/home/${USER}/AuroraPlatformSDK-${PSDK}/sdks/aurora_psdk"

# Install Flutter for Aurora OS
RUN test $(aurora-cli api --route="/flutter/install?version=${FLUTTER}" | grep "code" | tail -n 1 | xargs | sed 's/,//g' | sed 's/code: //g') -eq 200 || exit 1
ENV PATH="/home/${USER}/.local/opt/flutter-${FLUTTER}/bin:$PATH"
RUN flutter precache --aurora --force
RUN printf '{\n\
    "enable-aurora-devices": true,\n\
    "aurora-psdk-dir": "/home/'${USER}'/AuroraPlatformSDK-'${PSDK}'/sdks/aurora_psdk"\n\
}' >> /home/${USER}/.config/flutter/settings
